name: Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare WASM packages
        run: |
          python3 scripts/download-assets.py
        env:
          CI: "1"
      - name: Write env file
        run: |
          # We save env in Github secrets called "ENVIRONMENT_DATA"
          # Write into ./frontend/.env
          echo "$ENVIRONMENT_DATA" > ./frontend/.env
        env: 
          ENVIRONMENT_DATA: ${{ secrets.ENVIRONMENT_DATA }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run generate
      - name: Copy assets contents
        run: |
          touch ./frontend/.output/public/.nojekyll
      - name: Fix permissions
        run: |
          chmod -c -R +rX "./frontend/.output/public/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/.output/public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action